services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  B13\OnlineMediaUpdater\:
    resource: '../Classes/*'
  B13\OnlineMediaUpdater\EventListener\FileListEventListener:
    tags:
      - name: event.listener
        identifier: 'b13/online-media-updater/filelist-listener'
